USE study_buddy;
INSERT INTO Users (email, password, firstName, lastName, role, image) values ('test@test.com', 'test', 'test', 'test', 'Admin', 'https://cdn140.picsart.com/310767592149201.jpg?type=webp&to=crop&r=256');
INSERT INTO Users (email, password, firstName, lastName, role, image) values ('cristina@cristina.com', 'cristina', 'Cristina', 'Terry', 'Admin', 'https://media-exp1.licdn.com/dms/image/C4D03AQFaxqj0rTBR-Q/profile-displayphoto-shrink_200_200/0?e=1595462400&v=beta&t=fgQsiqeK6w_r2ltU-SizUL8F4p59vE5pNpxqIyFWxTQ');
INSERT INTO Users (email, password, firstName, lastName, role, image) values ('brad@brad.com', 'brad', 'Brad', 'Davis', 'Admin', 'https://media-exp1.licdn.com/dms/image/C5603AQFUm1pTViCp1w/profile-displayphoto-shrink_200_200/0?e=1595462400&v=beta&t=e0DfY23faeKtF9Rehlob49poE-Lr5nac5UeuHscN0uI');
INSERT INTO Users (email, password, firstName, lastName, role, image) values ('ta@ta.com', 'test', 'Teaching', 'Assistant', 'TA','');
INSERT INTO Users (email, password, firstName, lastName, role, image) values ('tjohnson@ucb.edu', 'test', 'Talitha', 'Johnson', 'Student', 'https://randomuser.me/api/portraits/women/6.jpg');
INSERT INTO Users (email, password, firstName, lastName, role, image) values ('jheath@ucb.edu', 'test', 'Jad', 'Heath', 'Student', 'https://randomuser.me/api/portraits/men/26.jpg');
INSERT INTO Users (email, password, firstName, lastName, role, image) values ('jmejia@ucb.edu', 'test', 'Jensen', 'Mejia', 'Student', 'https://randomuser.me/api/portraits/men/27.jpg');
INSERT INTO Users (email, password, firstName, lastName, role, image) values ('cbell@ucb.edu', 'test', 'Cynthia', 'Bell', 'Student', 'https://randomuser.me/api/portraits/women/7.jpg');
INSERT INTO Users (email, password, firstName, lastName, role, image) values ('bblackwell@ucb.edu', 'test', 'Braxton', 'Blackwell', 'Student', 'https://randomuser.me/api/portraits/men/28.jpg');
INSERT INTO Users (email, password, firstName, lastName, role, image) values ('oforster@ucb.edu', 'test', 'Olli', 'Forster', 'Student', 'https://randomuser.me/api/portraits/men/29.jpg');
INSERT INTO Users (email, password, firstName, lastName, role, image) values ('vhooper@ucb.edu', 'test', 'Varun', 'Hooper', 'Student', 'https://randomuser.me/api/portraits/men/30.jpg');
INSERT INTO Users (email, password, firstName, lastName, role, image) values ('swoodcock@ucb.edu', 'test', 'Sumayyah', 'Woodcock', 'Student', 'https://randomuser.me/api/portraits/women/8.jpg');
INSERT INTO Users (email, password, firstName, lastName, role, image) values ('ngarrett@ucb.edu', 'test', 'Niamh', 'Garrett', 'Student', 'https://randomuser.me/api/portraits/women/9.jpg');
INSERT INTO Users (email, password, firstName, lastName, role, image) values ('halvarez@ucb.edu', 'test', 'Harvey', 'Alvarez', 'Student', 'https://randomuser.me/api/portraits/men/31.jpg');
INSERT INTO Users (email, password, firstName, lastName, role, image) values ('ahastings@ucb.edu', 'test', 'Anne', 'Hastings', 'Student', 'https://randomuser.me/api/portraits/women/10.jpg');
INSERT INTO Users (email, password, firstName, lastName, role, image) values ('ahuerta@ucb.edu', 'test', 'Atlas', 'Huerta', 'Student', 'https://randomuser.me/api/portraits/men/32.jpg');
INSERT INTO Users (email, password, firstName, lastName, role, image) values ('hcraig@ucb.edu', 'test', 'Hashir', 'Craig', 'Student', 'https://randomuser.me/api/portraits/men/33.jpg');
INSERT INTO Users (email, password, firstName, lastName, role, image) values ('jknox@ucb.edu', 'test', 'Jannah', 'Knox', 'Student', 'https://randomuser.me/api/portraits/women/11.jpg');
INSERT INTO Users (email, password, firstName, lastName, role, image) values ('jcannon@ucb.edu', 'test', 'Joseff', 'Cannon', 'Student', 'https://randomuser.me/api/portraits/men/34.jpg');
INSERT INTO Users (email, password, firstName, lastName, role, image) values ('mrobertson@ucb.edu', 'test', 'Mari', 'Robertson', 'Student', 'https://randomuser.me/api/portraits/women/12.jpg');
INSERT INTO Users (email, password, firstName, lastName, role, image) values ('nwhitworth@ucb.edu', 'test', 'Natasha', 'Whitworth', 'Student', 'https://randomuser.me/api/portraits/women/13.jpg');
INSERT INTO Users (email, password, firstName, lastName, role, image) values ('ebaxter@ucb.edu', 'test', 'Emilio', 'Baxter', 'Student', 'https://randomuser.me/api/portraits/men/35.jpg');
INSERT INTO Users (email, password, firstName, lastName, role, image) values ('ramos@ucb.edu', 'test', 'Rafe', 'Amos', 'Student', 'https://randomuser.me/api/portraits/men/36.jpg');
INSERT INTO Users (email, password, firstName, lastName, role, image) values ('ashields@ucb.edu', 'test', 'Addison', 'Shields', 'Student', 'https://randomuser.me/api/portraits/women/14.jpg');
INSERT INTO Users (email, password, firstName, lastName, role, image) values ('ehutchinson@ucb.edu', 'test', 'Elise', 'Hutchinson', 'Student', 'https://randomuser.me/api/portraits/women/15.jpg');
INSERT INTO Users (email, password, firstName, lastName, role, image) values ('iparks@ucb.edu', 'test', 'Israel', 'Parks', 'Student', 'https://randomuser.me/api/portraits/men/37.jpg');
INSERT INTO Users (email, password, firstName, lastName, role, image) values ('ahawkins@ucb.edu', 'test', 'Aneesah', 'Hawkins', 'Student', 'https://randomuser.me/api/portraits/women/16.jpg');
INSERT INTO Users (email, password, firstName, lastName, role, image) values ('ameyer@ucb.edu', 'test', 'Asher', 'Meyer', 'Student', 'https://randomuser.me/api/portraits/men/38.jpg');
INSERT INTO Users (email, password, firstName, lastName, role, image) values ('kpatterson@ucb.edu', 'test', 'Kelly', 'Patterson', 'Student', 'https://randomuser.me/api/portraits/women/17.jpg');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('Accounting', '101', '', 'Leilani Macfarlane', 'Samuel Sharma');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('Accounting', '201', '', 'Amos Maguire', 'Leja Cardenas');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('Accounting', '302', '', 'Leilani Macfarlane', 'Liam French');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('Accounting', '402', '', 'Amos Maguire', 'Tania Huynh');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('Art History', '101', '', 'Kris Cantu', 'Aj Truong');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('Art History', '201', '', 'Sonia Miranda', 'Alayna Davey');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('Art History', '302', '', 'Kris Cantu', 'Lawson Carver');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('Art History', '402', '', 'Sonia Miranda', 'Sonya Daniels');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('Biology', '101', '', 'Alexia Butler', 'Erika Ewing');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('Biology', '201', '', 'Adaline Quinn', 'Macauley Calderon');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('Biology', '302', '', 'Alexia Butler', 'Kit Parrish');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('Biology', '402', '', 'Adaline Quinn', 'Phoenix Fleming');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('Chemistry', '101', '', 'Roksana Rutledge', 'Mekhi Strong');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('Chemistry', '201', '', 'Trent Adams', 'Stefania Romero');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('Chemistry', '302', '', 'Roksana Rutledge', 'Aarron Huber');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('Chemistry', '402', '', 'Trent Adams', 'Rudi Irwin');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('Computer Science', '101', '', 'Macauley Kim', 'Rima Hull');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('Computer Science', '201', '', 'Haley Hussain', 'Derren Beattie');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('Computer Science', '302', '', 'Macauley Kim', 'Nawal Emerson');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('Computer Science', '402', '', 'Haley Hussain', 'Chantelle Glass');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('Economics', '101', '', 'Susannah Owens', 'Melissa Downes');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('Economics', '201', '', 'Pascal Kelly', 'Taine Soto');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('Economics', '302', '', 'Susannah Owens', 'Mali Mcguire');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('Economics', '402', '', 'Pascal Kelly', 'Cade Forbes');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('Electrical Engineering', '101', '', 'Frances Glover', 'Blythe Vo');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('Electrical Engineering', '201', '', 'Kyal Woodley', 'Adina Sanders');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('Electrical Engineering', '302', '', 'Frances Glover', 'Marisa Mason');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('Electrical Engineering', '402', '', 'Kyal Woodley', 'Humera Broughton');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('English', '101', '', 'Charley Bautista', 'Avleen Hansen');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('English', '201', '', 'Aarron Petty', 'Ava-May Edwards');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('English', '302', '', 'Charley Bautista', 'Hakeem Dickerson');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('English', '402', '', 'Aarron Petty', 'Jamelia Garrett');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('Finance', '101', '', 'Dalton Trejo', 'Aahil Larsen');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('Finance', '201', '', 'Elinor Daugherty', 'Haleema Nash');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('Finance', '302', '', 'Dalton Trejo', 'Desiree Holloway');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('Finance', '402', '', 'Elinor Daugherty', 'Kane Conway');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('French', '101', '', 'Marguerite Zamora', 'Mathias Boone');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('French', '201', '', 'Timur Hackett', 'Khushi Handley');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('French', '302', '', 'Marguerite Zamora', 'Bryony Vargas');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('French', '402', '', 'Timur Hackett', 'Darren Archer');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('Full Stack', '101', '', 'Jerome Chenette', 'Kerwin Hy, Mahi Gunasekaran');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('History', '101', '', 'Brielle Willis', 'Eduardo Rodriguez');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('History', '201', '', 'Nabeel Handley', 'Michalina Olson');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('History', '302', '', 'Brielle Willis', 'Tyler-James Sanchez');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('History', '402', '', 'Nabeel Handley', 'Malikah Mckenna');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('Italian', '101', '', 'Keith Pruitt', 'Markus Whitehouse');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('Italian', '201', '', 'Leland Cummings', 'Harriette Mayo');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('Italian', '302', '', 'Keith Pruitt', 'Macie Kaye');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('Italian', '402', '', 'Leland Cummings', 'Mabel Moody');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('Management', '101', '', 'Kester Chen', 'Cecilia Randall');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('Management', '201', '', 'Awais Amin', 'Nel Wright');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('Management', '302', '', 'Kester Chen', 'Caris Palmer');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('Management', '402', '', 'Awais Amin', 'Sila Velez');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('Mathematics', '101', '', 'Jade Hussain', 'Daisy-Mae Piper');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('Mathematics', '201', '', 'Jay-Jay Weber', 'Asif Jordan');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('Mathematics', '302', '', 'Jade Hussain', 'Cienna Rahman');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('Mathematics', '402', '', 'Jay-Jay Weber', 'Sayed Franklin');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('Music', '101', '', 'Kristina Lovell', 'Kirstie Shields');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('Music', '201', '', 'Tadhg Barclay', 'Kobi Hensley');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('Music', '302', '', 'Kristina Lovell', 'Cally Perez');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('Music', '402', '', 'Tadhg Barclay', 'Dagwood Holland');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('Philosophy', '101', '', 'Rosalie Mccaffrey', 'Adele Elliott');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('Philosophy', '201', '', 'Aliyah Small', 'Cloe Allman');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('Philosophy', '302', '', 'Rosalie Mccaffrey', 'Amelie Dunne');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('Philosophy', '402', '', 'Aliyah Small', 'Sultan Owen');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('Physics', '101', '', 'Mahdi Buckner', 'Amit Naylor');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('Physics', '201', '', 'Maia Waters', 'Freddie Stephenson');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('Physics', '302', '', 'Mahdi Buckner', 'Havin Davie');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('Physics', '402', '', 'Maia Waters', 'Jordan Brown');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('Political Science', '101', '', 'Malakai Connor', 'Jaylan Hirst');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('Political Science', '201', '', 'Molly Whitaker', 'Arfa Plummer');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('Political Science', '302', '', 'Malakai Connor', 'Milla Hale');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('Political Science', '402', '', 'Molly Whitaker', 'Aronas Castaneda');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('Psychology', '101', '', 'Anthony Colon', 'Eliana Vickers');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('Psychology', '201', '', 'Merlin Robson', 'Daniaal Molloy');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('Psychology', '302', '', 'Anthony Colon', 'Jess Warner');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('Psychology', '402', '', 'Merlin Robson', 'Ela Prentice');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('Spanish', '101', '', 'Vera Hastings', 'Connar Shannon');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('Spanish', '201', '', 'Shona Good', 'Ricky Sanford');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('Spanish', '302', '', 'Vera Hastings', 'Dustin Reyes');
INSERT INTO Classes (subject, class, section, instructor, ta) values ('Spanish', '402', '', 'Shona Good', 'Kajol Page');
INSERT INTO Locations (subject, class, section, instructor, ta) values ('Virtual', '', 'None', '');
INSERT INTO Locations (subject, class, section, instructor, ta) values ('Bartle Library', '202', '10', 'No');
INSERT INTO Locations (subject, class, section, instructor, ta) values ('Bartle Library', '310', '8', 'No');
INSERT INTO Locations (subject, class, section, instructor, ta) values ('Bartle Library', '221', '20', 'No');
INSERT INTO Locations (subject, class, section, instructor, ta) values ('Eisnehower Hall', '165', '20', 'No');
INSERT INTO Locations (subject, class, section, instructor, ta) values ('Eisnehower Hall', '167', '20', 'No');
INSERT INTO Locations (subject, class, section, instructor, ta) values ('Eisnehower Hall', '169', '20', 'No');
INSERT INTO Locations (subject, class, section, instructor, ta) values ('Science Library', '335', '12', 'Yes');
INSERT INTO Locations (subject, class, section, instructor, ta) values ('Science Library', '337', '10', 'Yes');
INSERT INTO Locations (subject, class, section, instructor, ta) values ('Science Library', '339', '12', 'Yes');
INSERT INTO Locations (subject, class, section, instructor, ta) values ('Engineering', '312', '8', 'Yes');
INSERT INTO Locations (subject, class, section, instructor, ta) values ('Engineering', '314', '16', 'Yes');
INSERT INTO Locations (subject, class, section, instructor, ta) values ('Engineering', '316', '10', 'Yes');